# Configuration file 8: Convblocks + mbconv + no_op

QNAS:
    crossover_rate: 0.5
    max_generations: 300
    max_num_nodes: 20
    num_quantum_ind: 5
    penalize_number: 3
    repetition: 4
    replace_method: best
    update_quantum_gen: 5
    update_quantum_rate: 0.1
    save_data_freq: 10
    crossover_frequency: 5
    pop_crossover_rate: 0.4 # offspring replacement proportion in the population
    pop_crossover_method: hux # hux, uniform
    patience: 60


    params_ranges:
        decay: 0.9
        learning_rate: 0.001
        momentum: 0.0
        weight_decay: 1.0e-4

    function_dict:  {'conv_1_1_32':  {'function': 'ConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 32}, 'prob': 1.0/2.0/10.0},
                     'conv_1_1_64':  {'function': 'ConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 64}, 'prob': 1.0/2.0/10.0},
                     'conv_3_1_32':  {'function': 'ConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 32}, 'prob': 1.0/2.0/10.0},
                     'conv_3_1_64':  {'function': 'ConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 64}, 'prob': 1.0/2.0/10.0},
                     'mbconv_3_1_32':  {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 32}, 'prob': 1.0/2.0/10.0},
                     'mbconv_3_1_64':  {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 64}, 'prob': 1.0/2.0/10.0},
                     'mbconv_3_1_128': {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 128}, 'prob': 1.0/2.0/10.0},
                     'mbconv_3_1_256': {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 256}, 'prob': 1.0/2.0/10.0},
                     'mbconv_5_1_32':  {'function': 'MBConv', 'params': {'kernel': 5, 'strides': 1,  'filters': 32}, 'prob': 1.0/2.0/10.0},
                     'mbconv_5_1_64':  {'function': 'MBConv', 'params': {'kernel': 5, 'strides': 1,  'filters': 64}, 'prob': 1.0/2.0/10.0},
                     'no_op':        {'function': 'NoOp', 'params': {}, 'prob': 1.0/2.0}}

train:
    batch_size: 128
    eval_batch_size: 128
    max_epochs: 50
    epochs_to_eval: 5 
    optimizer: AdamW
    fitness_metric: best_loss
    mo_metric_base: loss
    mixed_precision: True
    available_gpus: [0, 1] # gpu0, gpu1, gpu2 [0, 1, 2]
    device: cuda:0

    # Dataset
    dataset: Cifar10
    data_augmentation: False
    subtract_mean: True
    limit_data: True
    limit_data_value: 10000
    num_workers: 4

    # Tensorflow
    save_checkpoints_epochs: 5
    save_summary_epochs: 0.25
    threads: 9

    # penalization parameters - scalarized fitness
    max_params: 1300000 # 1.3M
    max_inference_time: 6400 # us