# Configuration file 7: Convblocks + (depthwise + squeeze and excitation) Blocks

QNAS:
    crossover_rate: 0.5
    max_generations: 300
    max_num_nodes: 20
    num_quantum_ind: 5
    penalize_number: 3
    repetition: 4
    replace_method: best
    update_quantum_gen: 5
    update_quantum_rate: 0.1
    save_data_freq: 10
    crossover_frequency: 5
    pop_crossover_rate: 0.4 # offspring replacement proportion in the population
    pop_crossover_method: hux # hux, uniform
    patience: 60

    params_ranges:
        decay: 0.9
        learning_rate: 0.001
        momentum: 0.0
        weight_decay: 1.0e-4

    function_dict:  {
                    'conv_1_1_32':  {'function': 'ConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 32}, 'prob': 1.0/3.0/86.0},
                    'conv_1_1_64':  {'function': 'ConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'conv_3_1_32':  {'function': 'ConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 32}, 'prob': 1.0/3.0/86.0},
                    'conv_3_1_64':  {'function': 'ConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'conv_3_1_128': {'function': 'ConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 128}, 'prob': 1.0/3.0/86.0},
                    'conv_3_1_256': {'function': 'ConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 256}, 'prob': 1.0/3.0/86.0},
                    'conv_5_1_32':  {'function': 'ConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 32}, 'prob': 1.0/3.0/86.0},
                    'conv_5_1_64':  {'function': 'ConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},

                    'bv1_3_1_64':  {'function': 'ResidualV1', 'params': {'kernel': 3, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'bv1_3_1_128': {'function': 'ResidualV1', 'params': {'kernel': 3, 'strides': 1, 'filters': 128}, 'prob': 1.0/3.0/86.0},
                    'bv1_3_1_256': {'function': 'ResidualV1', 'params': {'kernel': 3, 'strides': 1, 'filters': 256}, 'prob': 1.0/3.0/86.0},
                    'bv1_5_1_64':  {'function': 'ResidualV1', 'params': {'kernel': 5, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'bv1_5_1_128': {'function': 'ResidualV1', 'params': {'kernel': 5, 'strides': 1, 'filters': 128}, 'prob': 1.0/3.0/86.0},
                    'bv1_5_1_256': {'function': 'ResidualV1', 'params': {'kernel': 5, 'strides': 1, 'filters': 256}, 'prob': 1.0/3.0/86.0},

                    'resv1cbam_3_1_64':  {'function': 'ResidualV1CBAM', 'params': {'kernel': 3, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'resv1cbam_3_1_128': {'function': 'ResidualV1CBAM', 'params': {'kernel': 3, 'strides': 1, 'filters': 128}, 'prob': 1.0/3.0/86.0},
                    'resv1cbam_3_1_256': {'function': 'ResidualV1CBAM', 'params': {'kernel': 3, 'strides': 1, 'filters': 256}, 'prob': 1.0/3.0/86.0},
                    'resv1cbam_5_1_64':  {'function': 'ResidualV1CBAM', 'params': {'kernel': 5, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'resv1cbam_5_1_128': {'function': 'ResidualV1CBAM', 'params': {'kernel': 5, 'strides': 1, 'filters': 128}, 'prob': 1.0/3.0/86.0},
                    'resv1cbam_5_1_256': {'function': 'ResidualV1CBAM', 'params': {'kernel': 5, 'strides': 1, 'filters': 256}, 'prob': 1.0/3.0/86.0},

                    'seconv_1_1_32':  {'function': 'SEConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 32, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'seconv_1_1_64':  {'function': 'SEConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 64, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_32':  {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 32, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_64':  {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 64, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_128': {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 128, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_256': {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 256, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'seconv_5_1_32':  {'function': 'SEConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 32, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'seconv_5_1_64':  {'function': 'SEConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 64, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},

                    'seconv_1_1_32_red4':  {'function': 'SEConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 32, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'seconv_1_1_64_red4':  {'function': 'SEConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 64, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_32_red4':  {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 32, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_64_red4':  {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 64, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_128_red4': {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 128,'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'seconv_3_1_256_red4': {'function': 'SEConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 256,'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'seconv_5_1_32_red4':  {'function': 'SEConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 32, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'seconv_5_1_64_red4':  {'function': 'SEConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 64, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},

                    'dconv_1_1_32':  {'function': 'DWConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 32}, 'prob': 1.0/3.0/86.0},
                    'dconv_1_1_64':  {'function': 'DWConvBlock', 'params': {'kernel': 1, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'dconv_3_1_32':  {'function': 'DWConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 32}, 'prob': 1.0/3.0/86.0},
                    'dconv_3_1_64':  {'function': 'DWConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},
                    'dconv_3_1_128': {'function': 'DWConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 128}, 'prob': 1.0/3.0/86.0},
                    'dconv_3_1_256': {'function': 'DWConvBlock', 'params': {'kernel': 3, 'strides': 1, 'filters': 256}, 'prob': 1.0/3.0/86.0},
                    'dconv_5_1_32':  {'function': 'DWConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 32}, 'prob': 1.0/3.0/86.0},
                    'dconv_5_1_64':  {'function': 'DWConvBlock', 'params': {'kernel': 5, 'strides': 1, 'filters': 64}, 'prob': 1.0/3.0/86.0},

                    'mbconv_3_1_32':  {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 32, 'expand_ratio': 6, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbconv_3_1_64':  {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 64, 'expand_ratio': 6, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbconv_3_1_128': {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 128,'expand_ratio': 6, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbconv_3_1_256': {'function': 'MBConv', 'params': {'kernel': 3, 'strides': 1,  'filters': 256,'expand_ratio': 6, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbconv_5_1_32':  {'function': 'MBConv', 'params': {'kernel': 5, 'strides': 1,  'filters': 32, 'expand_ratio': 6, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbconv_5_1_64':  {'function': 'MBConv', 'params': {'kernel': 5, 'strides': 1,  'filters': 64, 'expand_ratio': 6, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},

                    'mbeppga_3_1_32':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 32, 'expand_ratio': 6, 'reduction_ratio': 16 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_64':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 64, 'expand_ratio': 6, 'reduction_ratio': 16 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_128': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 128,'expand_ratio': 6, 'reduction_ratio': 16 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_256': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 256,'expand_ratio': 6, 'reduction_ratio': 16 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_32':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 32, 'expand_ratio': 6, 'reduction_ratio': 16 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_64':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 64, 'expand_ratio': 6, 'reduction_ratio': 16 }, 'prob': 1.0/3.0/86.0},

                    'mbeppga_3_1_32_expand3_red16':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 32, 'expand_ratio': 3, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_64_expand3_red16':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 64, 'expand_ratio': 3, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_128_expand3_red16': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 128,'expand_ratio': 3, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_256_expand3_red16': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 256,'expand_ratio': 3, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_32_expand3_red16':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 32, 'expand_ratio': 3, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_64_expand3_red16':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 64, 'expand_ratio': 3, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},

                    'mbeppga_3_1_32_expand4_red16':  {'function': 'MBConv_EPPGA','params':  {'kernel': 3, 'strides': 1,  'filters': 32, 'expand_ratio': 4, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_64_expand4_red16':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 64, 'expand_ratio': 4, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_128_expand4_red16': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 128,'expand_ratio': 4, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_256_expand4_red16': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 256,'expand_ratio': 4, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_32_expand4_red16':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 32, 'expand_ratio': 4, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_64_expand4_red16':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 64, 'expand_ratio': 4, 'reduction_ratio': 16}, 'prob': 1.0/3.0/86.0},
                     
                    'mbeppga_3_1_32_expand3_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 32, 'expand_ratio': 3, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_64_expand3_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 64, 'expand_ratio': 3, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_128_expand3_red4': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 128,'expand_ratio': 3, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_256_expand3_red4': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 256,'expand_ratio': 3, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_32_expand3_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 32, 'expand_ratio': 3, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_64_expand3_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 64, 'expand_ratio': 3, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},

                    'mbeppga_3_1_32_expand4_red4':  {'function': 'MBConv_EPPGA','params':  {'kernel': 3, 'strides': 1,  'filters': 32, 'expand_ratio': 4, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_64_expand4_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 64, 'expand_ratio': 4, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_128_expand4_red4': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 128,'expand_ratio': 4, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_256_expand4_red4': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 256,'expand_ratio': 4, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_32_expand4_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 32, 'expand_ratio': 4, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_64_expand4_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 64, 'expand_ratio': 4, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},

                    'mbeppga_3_1_32_expand6_red4':  {'function': 'MBConv_EPPGA','params':  {'kernel': 3, 'strides': 1,  'filters': 32, 'expand_ratio': 6, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_64_expand6_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 64, 'expand_ratio': 6, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_128_expand6_red4': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 128,'expand_ratio': 6, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_3_1_256_expand6_red4': {'function': 'MBConv_EPPGA', 'params': {'kernel': 3, 'strides': 1,  'filters': 256,'expand_ratio': 6, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_32_expand6_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 32, 'expand_ratio': 6, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},
                    'mbeppga_5_1_64_expand6_red4':  {'function': 'MBConv_EPPGA', 'params': {'kernel': 5, 'strides': 1,  'filters': 64, 'expand_ratio': 6, 'reduction_ratio': 4 }, 'prob': 1.0/3.0/86.0},


                    'max_pool_2_2': {'function': 'MaxPooling', 'params': {'kernel': 2, 'strides': 2}, 'prob': 1.0/3.0/2.0},
                    'avg_pool_2_2': {'function': 'AvgPooling', 'params': {'kernel': 2, 'strides': 2}, 'prob': 1.0/3.0/2.0},
                    'no_op':        {'function': 'NoOp', 'params': {}, 'prob': 1.0/3.0}}

train:
    batch_size: 256
    eval_batch_size: 256
    max_epochs: 50
    epochs_to_eval: 5 
    optimizer: AdamW
    fitness_metric: best_loss
    mo_metric_base: loss
    mixed_precision: True
    available_gpus: [0, 1] # gpu0, gpu1, gpu2 [0, 1, 2]
    device: cuda:0

    # Dataset
    dataset: Cifar10
    data_augmentation: False
    subtract_mean: True
    limit_data: True
    limit_data_value: 10000
    num_workers: 4

    # Tensorflow
    save_checkpoints_epochs: 5
    save_summary_epochs: 0.25
    threads: 20

    # penalization parameters - scalarized fitness
    max_params: 1300000 # 1.3M
    max_inference_time: 6400 # us

    # Network structure Configuration
    network_config: default
    network_gap: False